### ISSUE TITLE
Any good idea to import code from function layer when debug code locally?

### ISSUE THREAD

**Issue by AlexSun98** [allenheltondev/aws-lambda-layer-types#2]
hi @allenheltondev, ur blog looks great. thanks! I'm a bit new to lambda layer, so I got one question for you, 
How do you manage local debugging when the function needs to pull from function layer? do you modify environment path or do sth else? I think this code `require('/opt/nodejs/database'); ` doesn't work with local invocations by default... thanks 👍 

`// Pulls from Dependency Layer - Declared like normal
const short = require('short-uuid');
const httpStatusCode = require('http-status-codes');

// Pulls from Function Layer - Must pull from 'opt/nodejs/<filename>'
const db = require('/opt/nodejs/database'); 
`

**Comment by allenheltondev** [comment]
If you aren't using it already, I would highly recommend using the [SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html).

SAM will put layer contents where they need to go when running/debugging locally. All you would need to do is first build the service with `sam build` then run the command `sam local invoke <lambda name>` 

It should work locally no problem.
